Document: hash-identifier
Title: Debian hash-identifier Manual
Author: <insert document author here>
Abstract: This manual describes what hash-identifier is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hash-identifier/hash-identifier.sgml.gz

Format: postscript
Files: /usr/share/doc/hash-identifier/hash-identifier.ps.gz

Format: text
Files: /usr/share/doc/hash-identifier/hash-identifier.text.gz

Format: HTML
Index: /usr/share/doc/hash-identifier/html/index.html
Files: /usr/share/doc/hash-identifier/html/*.html
